<a href="https://colab.research.google.com/github/harshnegi02/numpy-study/blob/main/3_1_numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy basics


In [ ]:
! import numpy as np

/bin/bash: line 1: import: command not found


In [ ]:
import numpy as np

list vs numpy - Time taken


In [ ]:
from time import process_time

In [ ]:
python_list=[i for i in range(10000)]

start_time=process_time()

python_list=[i+5 for i in python_list]

end_time=process_time()

print(end_time-start_time)


0.0006848210000001131


In [ ]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()

np_array+=5
end_time=process_time()

print(end_time-start_time)


0.00017099200000103565


creating numpy array and performing opeartions


In [ ]:
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#creating a one dimension array
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a.shape

(5,)

In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

initial placeholders in numpy

In [ ]:
#create a numpy array of 0
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#array of a particular value
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#creating identity matrix
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#random integer value in specific range
b=np.random.randint(10,100,(3,5))
print(b)

[[28 24 90 65 51]
 [62 66 80 56 97]
 [98 62 39 15 39]]


In [ ]:
#array of evenly spaced value
d=np.linspace(10,35,5)
print(d)

[10.   16.25 22.5  28.75 35.  ]


In [ ]:
#convert list to array
list2=[10,20,30,40,50]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Mathematical operation in numpy array


In [ ]:
list1=[1,2,3,4,5]
list2=[7,8,9,10]

print(list1+list2) # + concat array

[1, 2, 3, 4, 5, 7, 8, 9, 10]


In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[2 0 5]
 [9 5 6]
 [5 3 7]]
[[16 16 10]
 [15 15 14]
 [12 12 10]]


In [ ]:
print(a+b)

[[18 16 15]
 [24 20 20]
 [17 15 17]]


In [ ]:
print(a-b)
print(a*b)
print(a/b)

[[-14 -16  -5]
 [ -6 -10  -8]
 [ -7  -9  -3]]
[[ 32   0  50]
 [135  75  84]
 [ 60  36  70]]
[[0.125      0.         0.5       ]
 [0.6        0.33333333 0.42857143]
 [0.41666667 0.25       0.7       ]]


Array multiplication


In [ ]:
array =np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 9 7]
 [2 1 1]]
(2, 3)


In [ ]:
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[4 2]
 [9 1]
 [7 1]]
(3, 2)
